name       : noise
version    : 0.4.2
release    : 14
source     :
    - git|https://github.com/elementary/music.git : 93b45982afa65c8127d1471b6541d3b6d1d8a335
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Noise Music Player
description: |
    The Noise Music Player designed for elementary OS
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgda-5.0)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(taglib_c)
    - pkgconfig(zeitgeist-2.0)
    - desktop-file-utils
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-Solus-defaults.patch
    %meson_configure -Dplugins=audioplayer,cdrom,ipod
build      : |
    %ninja_build
install    : |
    %ninja_install
