name       : noise
version    : 0.4.2
release    : 13
source     :
    - https://github.com/elementary/music/archive/0.4.2.tar.gz : 9e707e52da12eeb89b42630c697ac0adfefd20a0a12eac37ff3c65b106e0c9d3
license    : GPL-3.0
component  : multimedia.audio
summary    : Noise Music Player
description: |
    The Noise Music Player designed for elementary OS
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgda-5.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(taglib_c)
    - pkgconfig(zeitgeist-2.0)
    - desktop-file-utils
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-Close-While-Playing-so-the-user-can-actually-clo.patch
    %patch -p1 < $pkgfiles/0001-Tweak-AppData-to-improve-discoverability-under-Solus.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
