name       : noise
version    : 0.4
release    : 7
source     :
    - https://launchpad.net/noise/0.4.x/0.4/+download/noise-0.4.tar.xz : ae7b1f07df1f1e773c602cad224188ebc26799f1b759525b114edc698d044ab1
license    : GPL-3.0
component  : multimedia.audio
summary    : Noise Music Player
description: |
    The Pantheon Music Player designed for elementary OS
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgda-5.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(taglib_c)
    - pkgconfig(zeitgeist-2.0)
    - desktop-file-utils
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
