name       : noise
version    : 0.4.0.3
release    : 8
source     :
    - https://launchpad.net/noise/0.4.x/0.4.0.3/+download/noise-0.4.0.3.tar.xz : 9eb0aa8370d60e8cba289bce2b4df7c9c8a52fecfce637260c05f20d2efec27c
license    : GPL-3.0
component  : multimedia.audio
summary    : Noise Music Player
description: |
    The Pantheon Music Player designed for elementary OS
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgda-5.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(taglib_c)
    - pkgconfig(zeitgeist-2.0)
    - desktop-file-utils
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
