name       : noise
version    : 0.4.1
release    : 10
source     :
    - https://github.com/elementary/music/archive/0.4.1.tar.gz : cd7020b8ee3bb878ff1686a86a808b06ea51f08132152c3e27b10998e8b16f77
license    : GPL-3.0
component  : multimedia.audio
summary    : Noise Music Player
description: |
    The Pantheon Music Player designed for elementary OS
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgda-5.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(taglib_c)
    - pkgconfig(zeitgeist-2.0)
    - desktop-file-utils
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-Close-While-Playing-so-the-user-can-actually-clo.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
